#!/usr/bin/env node
'use strict';
/**
 * build-wiremap.js — inject the Wire Map core into wiremap.html.
 *
 * Same principle as tools/build-calc.js, and deliberately the same shape so
 * there is one build idiom in the project rather than two: the modules under
 * src/wiremap/ are authoritative, the browser bundle is generated from them,
 * and a stale bundle fails the build check.
 *
 * WHY THIS EXISTS
 * ---------------
 * Without it, wiremap.html would need its own copy of the model, geometry and
 * viewport logic. That is exactly how the calculator picked up three separate
 * defects: a rule written once in a tested module and again, differently, in
 * production. This step closes that door before any Wire Map feature is built.
 *
 * Module sources are embedded VERBATIM inside a small CommonJS shim, so the
 * code running in the browser is byte-for-byte the code the tests require().
 * Output is a pure function of the sources: explicit module order, no directory
 * scanning, no timestamps, no volatile hashes.
 *
 * Usage:
 *   node tools/build-wiremap.js          write the block into wiremap.html
 *   node tools/build-wiremap.js --check  verify only; exit 1 if stale
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const APP = path.join(ROOT, 'wiremap.html');

const START = '<!-- WM-CORE:START — generated, do not edit by hand -->';
const END = '<!-- WM-CORE:END -->';

/**
 * Explicit dependency order — NOT a directory scan. A glob would reorder on a
 * different filesystem and silently produce a different bundle.
 *
 * Later modules may require() earlier ones by relative path, so store.js in
 * WM-2 can depend on model.js with no change to this loader.
 */
const MODULES = [
  'model',
  'geometry',
  'viewport',
  'store',
];

function readModule(name) {
  const file = path.join(ROOT, 'src', 'wiremap', `${name}.js`);
  if (!fs.existsSync(file)) throw new Error(`missing module: ${file}`);
  // Normalise line endings only. Content is otherwise untouched.
  return fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n').replace(/\s+$/, '');
}

function buildBlock() {
  const parts = MODULES.map((name) => {
    const src = readModule(name);
    return [
      `  // ---- src/wiremap/${name}.js ----`,
      `  __reg[${JSON.stringify(name)}] = function (module, exports, require) {`,
      src.split('\n').map((l) => (l ? '    ' + l : '')).join('\n'),
      '  };',
    ].join('\n');
  });

  return [
    START,
    '<script>',
    '/* GENERATED by tools/build-wiremap.js — edit src/wiremap/*.js instead.',
    '   Those modules are the source of truth and are covered by the Node test',
    '   suite; this block is a verbatim copy of them wrapped in a CommonJS shim.',
    '   Run `npm run build:wiremap` after changing any Wire Map source.',
    '   `npm run build:wiremap:check` fails if this block is stale. */',
    'window.WM = (function () {',
    '  "use strict";',
    '  var __reg = {}, __cache = {};',
    '  function __require(p) {',
    '    var key = String(p).replace(/^\\.\\//, "").replace(/\\.js$/, "");',
    '    if (__cache[key]) return __cache[key].exports;',
    '    if (!__reg[key]) throw new Error("WM: unknown module " + key);',
    '    var m = { exports: {} };',
    '    __cache[key] = m;',
    '    __reg[key](m, m.exports, __require);',
    '    return m.exports;',
    '  }',
    '',
    parts.join('\n\n'),
    '',
    '  var api = {};',
    MODULES.map((n) => `  api[${JSON.stringify(n)}] = __require(${JSON.stringify(n)});`).join('\n'),
    '  return api;',
    '})();',
    '</script>',
    END,
  ].join('\n');
}

function main() {
  const check = process.argv.includes('--check');

  if (!fs.existsSync(APP)) {
    console.error(`ERROR: cannot find ${APP}`);
    console.error('wiremap.html is expected in the repository root.');
    process.exit(2);
  }

  const html = fs.readFileSync(APP, 'utf8');
  const block = buildBlock();

  const s = html.indexOf(START);
  const e = html.indexOf(END);

  if (s === -1 || e === -1) {
    if (check) {
      console.error('WIREMAP BUILD CHECK FAILED: markers not found in wiremap.html.');
      console.error('The Wire Map core has never been injected. Run: npm run build:wiremap');
      process.exit(1);
    }
    console.error('ERROR: markers not found in wiremap.html.');
    console.error(`Insert these two lines where the core should go:\n  ${START}\n  ${END}`);
    process.exit(2);
  }

  const current = html.slice(s, e + END.length);

  if (check) {
    if (current === block) {
      console.log('WIREMAP BUILD CHECK OK — wiremap.html matches src/wiremap/*.js');
      process.exit(0);
    }
    console.error('WIREMAP BUILD CHECK FAILED — wiremap.html is STALE.');
    console.error('The injected core does not match the current sources.');
    console.error(`  generated block: ${block.length} bytes`);
    console.error(`  block in app:    ${current.length} bytes`);
    console.error('Run `npm run build:wiremap` and commit wiremap.html before deploying.');
    process.exit(1);
  }

  if (current === block) {
    console.log('wiremap.html already up to date — nothing written.');
    return;
  }

  fs.writeFileSync(APP, html.slice(0, s) + block + html.slice(e + END.length));
  console.log(`Injected Wire Map core into wiremap.html (${block.length} bytes, ${MODULES.length} modules).`);
}

main();
