#!/usr/bin/env node
'use strict';
/**
 * build-calc.js — inject the deterministic calculator engine into mobile.html.
 *
 * WHY INJECT RATHER THAN LINK
 * ---------------------------
 * mobile.html is a single-file offline PWA. Loading the engine with
 * <script src="..."> would add a runtime network request and a new entry that
 * sw.js must cache; if that cache list were ever out of step the app would work
 * online and fail silently offline — the exact place where electricians need it.
 * Injecting keeps one file, no new requests, and leaves sw.js untouched.
 *
 * HOW IT STAYS HONEST
 * -------------------
 * Module sources are embedded VERBATIM inside a tiny CommonJS shim. Nothing is
 * rewritten, regex-stripped or reformatted, so the code executing in the
 * browser is byte-for-byte the code the tests require(). Output is a pure
 * function of the sources: no timestamps, no hashes of anything volatile, no
 * directory scanning. Same inputs always produce the same bytes.
 *
 * Usage:
 *   node tools/build-calc.js          write the block into mobile.html
 *   node tools/build-calc.js --check  verify only; exit 1 if stale
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const APP = path.join(ROOT, 'mobile.html');

const START = '<!-- EC-CALC:START — generated, do not edit by hand -->';
const END = '<!-- EC-CALC:END -->';

/**
 * Explicit dependency order. NOT a directory scan — a glob would reorder on a
 * different filesystem and silently produce a different bundle.
 */
const MODULES = [
  'tables',
  'ampacity',
  'voltageDrop',
  'conduitFill',
  'boxFill',
  'motor',
  'grounding',
  'wireSizing',
  'pullBox',
];

function readModule(name) {
  const file = path.join(ROOT, 'src', 'calc', `${name}.js`);
  if (!fs.existsSync(file)) throw new Error(`missing module: ${file}`);
  // Normalise line endings only. Content is otherwise untouched.
  return fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n').replace(/\s+$/, '');
}

function buildBlock() {
  const parts = MODULES.map((name) => {
    const src = readModule(name);
    return [
      `  // ---- src/calc/${name}.js ----`,
      `  __reg[${JSON.stringify(name)}] = function (module, exports, require) {`,
      src.split('\n').map((l) => (l ? '    ' + l : '')).join('\n'),
      '  };',
    ].join('\n');
  });

  return [
    START,
    '<script>',
    '/* GENERATED by tools/build-calc.js — edit src/calc/*.js instead.',
    '   Run `npm run build` after changing any calculator source.',
    '   `npm run build:check` fails if this block is stale. */',
    'window.EC = (function () {',
    '  "use strict";',
    '  var __reg = {}, __cache = {};',
    '  function __require(p) {',
    '    var key = String(p).replace(/^\\.\\//, "").replace(/\\.js$/, "");',
    '    if (__cache[key]) return __cache[key].exports;',
    '    if (!__reg[key]) throw new Error("EC: unknown module " + key);',
    '    var m = { exports: {} };',
    '    __cache[key] = m;',
    '    __reg[key](m, m.exports, __require);',
    '    return m.exports;',
    '  }',
    '',
    parts.join('\n\n'),
    '',
    '  var api = {};',
    MODULES.map((n) => `  api[${JSON.stringify(n)}] = __require(${JSON.stringify(n)});`).join('\n'),
    '  return api;',
    '})();',
    '</script>',
    END,
  ].join('\n');
}

function main() {
  const check = process.argv.includes('--check');

  if (!fs.existsSync(APP)) {
    console.error(`ERROR: cannot find ${APP}`);
    console.error('mobile.html is expected in the repository root, beside package.json.');
    process.exit(2);
  }

  const html = fs.readFileSync(APP, 'utf8');
  const block = buildBlock();

  const s = html.indexOf(START);
  const e = html.indexOf(END);

  if (s === -1 || e === -1) {
    if (check) {
      console.error('BUILD CHECK FAILED: markers not found in mobile.html.');
      console.error('The calculator engine has never been injected. Run: npm run build');
      process.exit(1);
    }
    console.error('ERROR: markers not found in mobile.html.');
    console.error(`Insert these two lines where the engine should go:\n  ${START}\n  ${END}`);
    process.exit(2);
  }

  const current = html.slice(s, e + END.length);

  if (check) {
    if (current === block) {
      console.log('BUILD CHECK OK — mobile.html matches src/calc/*.js');
      process.exit(0);
    }
    console.error('BUILD CHECK FAILED — mobile.html is STALE.');
    console.error('The injected engine does not match the current sources.');
    console.error(`  generated block: ${block.length} bytes`);
    console.error(`  block in app:    ${current.length} bytes`);
    console.error('Run `npm run build` and commit mobile.html before deploying.');
    process.exit(1);
  }

  if (current === block) {
    console.log('mobile.html already up to date — nothing written.');
    return;
  }

  fs.writeFileSync(APP, html.slice(0, s) + block + html.slice(e + END.length));
  console.log(`Injected calculator engine into mobile.html (${block.length} bytes, ${MODULES.length} modules).`);
}

main();
